language: node_js
node_js:
- '8'
- '10'
- '12'
script:
- npm run test:coverage
- codecov -f ./reports/coverage/*.json
jobs:
  include:
  - stage: npm release
    node_js: '10'
    script: npm run build
    deploy:
      provider: npm
      email: thiago@cruxframework.org
      skip_cleanup: true
      api_key:
        secure: nZOxHv8kWg+f3RZF6xMY8J8y/qTuVzWWpYDVz6Gjp+CS6yZSpFyfrlEp9/VVahLvkCckTKtrYtnaJwRGwnwx2RA2aiMaYYXCqxYzrTkH6yQjc67poKfd1/BOq655LuitZ92hgD9dvHCtjoBxLpNU9flzT3Osu/Td0sHI73lEeaBFJnUkq0Ui5w1mjwYboWKUqs6Kmv7RoAQaeEGwroUMg/Jvn0yguxyj0j6MZ2SVLAcULA9NhGhel3cxZB3ESraAEe6jkLTrVmDZA5jYEpI2PujbDK3ExMcjujpRGaauqh6Zsg+lDs6BWEWwvn8qHOiB/IIS9dYaX75Mmrpq4Kfi7DGtUkmrFIbUcpWef7cECeTSK5/BVcgHednymPYG6vQWF7/7pg6EpCz/L5dTy9Kvtsg1KbFhxiCejN4D4Bt1wdocBQ8IMA0FE4eowbdJ4odOi5olVSV2zPP/V8HS8W5mwU/3JZhLe91aCfQgw8EtMNi8IrEmtKKqo7878O81BGaFYQ2tbBFctEHYiPeQ3c+RPoWDs/NmRJY3UhM4NbC3cZrfq4S4UGxfTN+g1zelbv5UBZyRGRK99H30Rt4AaCzkwyp+2mJCqgxA4WrdNzNp+jXsujDM0o0/9GGyuSDb3bGUYCkeLSVvwwavv1YacY/elaBfJPV+ZIDfBYbJpe7P54Y=
      on:
        tags: true
        repo: thiagobustamante/typescript-rest
